baseURL = "http://salvador.devopsdays.com.br/" #por enquanto não usamos essa configuração
languageCode = "pt-br" #por enquanto não usamos essa configuração
title = "DevOpsDays Salvador 2017"
theme = "devopsdayspoa"

[params]
description = "Evento da cultura DevOps que irá se realizar na cidade de salvador" #irá preencher o meta description
slider = "enable" #qualquer coisa que não seja "enable" irá desabilitar o slider (as imagens que ficam correndo atrás do logo/nome do evento)
slider_selector = "disable" #qualquer coisa que não seja "enable" irá desabilitar os seletores
slider_sidecontrols = "disable" #qualquer coisa que não seja "enable" irá desabilitar os controles
intro_image = "logo_salvador.svg" #apenas o nome da imagem, deve estar em img/intro/
link_c4p = "https://docs.google.com/forms/d/e/1FAIpQLScJh3u2lLvorxGFfW_Uki2yfPG7tQHc65iMgiTHk9ZK5V6X-g/viewform" #endereço para o form/sistema de call4papers

email = "organizers-salvador-2017@devopsdays.org" #email da organização do email
twitter = "devopsdaysssa" #para https://www.twitter.com/nao-existe colocar apenas "não-existe"
facebook = "devopsdaysssa" #para https://www.facebook.com/nao-existe colocar apenas "não-existe"

#Os próximos 3 parametros aceitam tags html (ex: <br>) e markdown (ex: **negrito**)
quando = "28 de Outubro de 2017"
onde = "[Agilize Contabilidade Online](https://www.agilize.com.br/)<br>Alameda Salvador, 1057"
quanto = "Em breve mais informações"

#latitude e longitude podem ser pegos no google maps mesmo :)
#o mapa irá ficar centralizado nessas coordenadas E irá colocar o marcador exatamente sobre
mapa_latitude = -12.9774850
mapa_longitude = -38.4574100
mapa_zoom = 17 #nível de zoom que será apresentado o mapa
mapa_draggable = true #o mapa poderá ser arrastado?
mapa_zoomControl = true #mostrar o controle de zoom?
mapa_scrollwheel = false #a roda de rolagem do mouse deve poder alterar o zoom?
mapa_disableDoubleClickZoom = true #vou ser sincero, não entendi o que isso faz, hahaha
mapa_key = "AIzaSyCZgSdqxA3s-WhsIkB7TLQ4T4Z0Yz3oxH8" #chave na api do google, lembre de permitir o uso no google maps e afins!

status_ingressos = "disponiveis" #qualquer coisa que não seja "disponiveis" irá mostrar o aviso
aviso_status_ingressos = ""

status_programacao = "indisponivel" #qualquer coisa que não seja "disponivel" irá mostrar o aviso
aviso_status_programacao = ""
